namespace Triton.Game.Mapping
{
    using System;

    public enum ActorStateType
    {
        NONE,
        CARD_IDLE,
        CARD_MOUSE_OVER,
        CARD_OPPONENT_MOUSE_OVER,
        CARD_SELECTABLE,
        CARD_SELECTED,
        CARD_PLAYABLE,
        CARD_PLAYABLE_MOUSE_OVER,
        CARD_OVER_PLAYFIELD,
        CARD_COMBO,
        CARD_COMBO_MOUSE_OVER,
        CARD_TARGETABLE_BAD,
        CARD_TARGETABLE,
        ENDTURN_NO_MORE_PLAYS,
        ENDTURN_YOUR_TURN,
        ENDTURN_WAITING,
        CARD_POWERED_UP,
        zzz_ENDTURN_NO_MORE_PLAYS_MOUSE_OVER_DEPRECATED,
        zzz_ENDTURN_NMP_MOUSE_OVER_2_NMP_DEPRECATED,
        zzz_ENDTURN_YT_MOUSE_OVER_2_YT_DEPRECATED,
        ENDTURN_NMP_2_WAITING,
        DEPRECATED_ENDTURN_WAITING_2_NMP,
        ENDTURN_YOUR_TURN_TIMER,
        ENDTURN_WAITING_TIMER,
        CARD_RECENTLY_ACQUIRED,
        CARD_RECENTLY_ACQUIRED_MOUSE_OVER,
        CARD_VALID_TARGET,
        CARD_VALID_TARGET_MOUSE_OVER,
        CARD_HISTORY,
        HIGHLIGHT_OFF,
        HIGHLIGHT_PRIMARY_ACTIVE,
        HIGHLIGHT_PRIMARY_MOUSE_OVER,
        HIGHLIGHT_PRIMARY_MOUSE_DOWN,
        HIGHLIGHT_SECONDARY_ACTIVE,
        HIGHLIGHT_SECONDARY_MOUSE_OVER,
        HIGHLIGHT_SECONDARY_MOUSE_DOWN,
        HIGHLIGHT_MOUSE_OVER,
        ENDTURN_YOUR_TURN_EXPLODE_FX
    }
}

